opensky:
  username: ${OPENSKY_USERNAME}
  password: ${OPENSKY_PASSWORD}
  polling_interval_seconds: 10

paths:
  base: "${LOCAL_PATH}/datalake"
  bronze: "${LOCAL_PATH}/datalake/bronze/opensky"
  silver: "${LOCAL_PATH}/datalake/silver/opensky"
  gold: "${LOCAL_PATH}/datalake/gold/opensky"

  checkpoint_base: "${LOCAL_PATH}/datalake/_checkpoints"
  bronze_checkpoint: "${LOCAL_PATH}/datalake/_checkpoints/bronze/opensky"
  silver_checkpoint: "${LOCAL_PATH}/datalake/_checkpoints/silver/opensky"
  gold_checkpoint: "${LOCAL_PATH}/datalake/_checkpoints/gold/opensky"

streaming:
  trigger_interval: "30 seconds"
  checkpoint_retention_days: 7

delta:
  mode: "append"
  merge_schema: false

logging:
  level: "INFO"